INSERT INTO TBL_CIDADE(NOME, ESTADO, POP, PIB) VALUES('Itapevi', 'Sao Paulo', '100', '1');
INSERT INTO TBL_CIDADE(NOME, ESTADO, POP, PIB) VALUES('Itapevi', 'Sao Paulo', '100', '1');
INSERT INTO TBL_CIDADE(NOME, ESTADO, POP, PIB) VALUES('Ita', 'Sao ', '100', '1');